### PR TITLE
Request to add names collected from NYS swimming results

### PR DESCRIPTION
**Pull request by gpilgrim2670**
I've pulled first names from a repository of New York state high school swimming results 2000-2020.  Approximately 2800 names that were not already somewhere in names.csv were added to the first column.  The first column was then resorted alphabetically.

Happy to make changes etc. as needed

### CODE REVIEW

**Comment by carltonnorthern** [comment]
I appreciate the addition of new first names but I think without the accompanying nicknames/diminutive names it may just make things more complicated .  Do you think you may be able to manually add nicknames/diminutive names?  Also, what is the reasoning for the exactly 3 nicknames/diminutive names?

**Comment by gpilgrim2670** [comment]
Fair points, let me look into it and get back to you

**Comment by gpilgrim2670** [comment]
@carltonnorthern alright let's try that again, this time with only the names that have diminutives and with all the columns

**Comment by carltonnorthern** [comment]
Well done!  Thank you for the contribution.

**Pull request merged**
