### PR TITLE
Add python package, tests, and normalizer script

### LINKED ISSUE #33: Make release on PyPI
Hi! This looks to me to be one of the better maintained datasets of diminutive names on GitHub. It could be easier to use in python if this was actually released on PyPI so people could do a `pip install nicknames` (surprisingly this package name isn't taken? Could definitely choose another name too.)

If I open a PR for this, would you be open to it? I'd add a github action similar to [this one](https://github.com/dedupeio/dedupe/blob/master/.github/workflows/pythonpackage.yml#L60) that would build and release the wheels automatically on a git tag. Your admin overhead on a day-to-day would be minimal, you'd just have to set up an PyPI account and add the access token to this repo's Secrets once. I can help with this too if you want.

Thank you!

### PR DESCRIPTION
**Pull request by NickCrews**
Closes #33 

@carltonnorthern couple thoughts:

- Please enable github actions so you can see the CI runs. You can see example runs at https://github.com/NickCrews/nickname-and-diminutive-names-lookup/actions
- Need to add your email as maintainer. Let me know what it is and I can add it to pyproject.toml
- Let me know your PyPI username and I can invite you as maintainer of https://test.pypi.org/project/us-nicknames and https://pypi.org/project/us-nicknames/. Then you can create an API token for each of them and add them repository secrets. 5 minutes of effort.
- Could put the python README in the python folder, so the python info isn't cluttering up the root README
- Hopefully you agree with how the name list is normalized. It doesn't change the python behavior, but perhaps it changes the behavior of other parsers. Before, I think the first entry of each line was supposed to be the "canonical" name, with the rest on the line being the nickname. But, that's not how the python implementation actually treated it. Python treated is as though all the names on a single line are interchangeable. Not sure which we prefer.

### CODE REVIEW

**Comment by mdahlman** [comment]
FWIW: Regarding your line, "I think the first entry of each line was supposed to be the "canonical" name".
I believe that the original intent long enough ago was exactly as you suggest. It was expected to be the canonical name in the first position.
But from my use of the data set, that idea is theoretically desirable... but impossible in practice. For example:
Elliott vs Elliot (there's really no reason to consider one more canonical)
Anna vs Ana (same)
John vs Jack (historically, in the US, John was canonical, and Jack was a nickname. This is no longer the case.)

So I vote that the "correct" guidance to use the data set would be to always consider all names on a line as interchangeable.

**Comment by NickCrews** [comment]
@mdahlman Thanks for your thoughts. That makes sense how that could be a problem. If distinguishing between canonical vs nickname was important though, we could fix those problematic cases by adding multiple lines, eg have an `anna,ana` as well as an `ana,anna` line. Then for the non-symmetrical cases, we just have one line, eg we have `genevieve,gen` but not `gen,genevieve`. If the data had supported it, would you have appreciated being able to distinguish?

I'm thinking that distinguishing would allow these use cases:
1. `def nick_names(name: str) -> set[str]` eg `ana -> {anna}`, `anna -> {ana}`, `genevieve -> {gen}`, `gen -> {}`
2. `def canonical_names(name: str) -> set[str]` eg `ana -> {anna}`, `anna -> {ana}`, `genevieve -> {}`, `gen -> {genevieve}`
3. `def all_names(name: str) -> set[str]: nick_names(name: str) | canonical_names(name: str)`
Are there other uses that I'm missing? Would there be a better API?

**Comment by mdahlman** [comment]
And to finish your # 3 with an example parallel to the others, I think it would be this:
eg `ana -> {anna}`, `anna -> {ana}`, `genevieve -> {gen}`, `gen -> {genevieve}`

Yes, being able to distinguish nickname vs canonical name would be useful in some cases.

Also, my example of ana/anna was terrible. There is no corresponding line in this data set, so I only introduced confusion by using that exact example. Sorry about that. (But the equivalent certainly exists in pairs like jerry/geraldine.)

Instead, consider these 3 lines actually from the dataset:
jackson,jack
jacqueline,jackie,jack
john,jack,johnny,jock,ian

Therefore I think your examples would be as follows:

1. nick_names: `jack -> {}`, `jackson -> {jack}`, `jacqueline -> {jackie,jack}
2. canonical_names: `jack -> {jackson, jacqueline, john}`, `jackson -> {}`
3. all_names: `jack -> {jackson, jacqueline, jackie, john, johnny, jock, ian}`

Those are useful.

The method that would be **most** useful to me would be something like this:
`def canonical_name_best_guess(name: str, gender: str=unknown) -> str`

This data set can't support this API today. It doesn't have gender, and it doesn't have the idea of one canonical name being more likely than another. But if one were looking to the future, that's the method I would want.

**Comment by NickCrews** [comment]
naw I understood what you meant, no worries! 

Note that your example of `all_names(jack) -> {jackson, jacqueline, jackie, john, johnny, jock, ian}` is slightly different from the implementation I said of `all_names` being the union of `nick_names` and `canonical_names`, because it contains jackie, john, johnny, jock, and ian. If it followed my implementation, you would just get `all_names(jack) -> {jackson, jacqueline, john}`

Not to say which is superior. It depends on if names adhere to the transitive property: If both names B and C are nicknames for A, does that mean that B and C can be used interchangeably? For instance, looking through the current csv, "lisa" and "mel" are both short for "melissa", but I'm hesitant to say it's common that someone named "lisa" uses the nickname "mel".

If we keep the current python implementation that assumes each line is an equivalence class, this melissa line should probably get split up into separate lines, eg `melissa,lisa` and `melissa,mel`.

**Comment by carltonnorthern** [comment]
@NickCrews excellent work!  

My e-mail address is carlton.northern@gmail.com and my PyPi account is carlton.northern.

I think once I approve your PR it may allow you to set up actions but we'll have to see.

I think keeping the new additions to the current README is fine.

I'll comment separately on the semantics discussion but I love it so far.

**Comment by carltonnorthern** [comment]
So, I agree with the idea that the first name on a line is supposed to be the canonical name and the following names are nicknames (even though the dataset doesn't always bear that out).  I do like the proposal that if we think names are interchangeable that there be two entries `John -> Jack`, `Jack -> John`, etc.

If we go with the `all_names(jack) -> {jackson, jacqueline, john}` how is that different from `canonical_names`?  I could see it being potentially useful to return all the names of lines in which `Jack` appears in cases where you may want to see all the names that have some relation, even though it's not clear what that relation is.

**Comment by carltonnorthern** [comment]
Honestly, I think one of the hardest problems for me, and probably why I haven't tried to revamp the dataset to differentiate canonical names is alternate spellings.  I think `Anna` is a perfect example of this.

We have `anna,anne,ann,annie,nan` where I think `anna`, `anne`, `ann`, 'annie' could all be the canonical names. So, do we need an entry for each of these and then duplicate the nicknames?

**Comment by NickCrews** [comment]
@carltonnorthern I invited you as owner of the pypi project, but you don't seem to be registered on the test.pypi server. Make an account there and I'll try again.

PR incoming to add your email.

**Comment by NickCrews** [comment]
> If we go with the all_names(jack) -> {jackson, jacqueline, john} how is that different from canonical_names?

For Jack, you're right there is no difference. But for say

alex,al
alexander,alex,al
alexandra,alex,all

Then
- canonical_names(alex) -> {alexander,alexandra} eg all of the names that alex could be a nickname for
- nick_names(alex) -> {al} eg all of the names that you could use as nicknames for alex
- and all_names(alex) -> {al, alexander, alexandra} eg the union of these two, all of the names that are interchangeable with alex. This is what the current python implementation does.

**Comment by NickCrews** [comment]
> We have anna,anne,ann,annie,nan where I think anna, anne, ann, 'annie' could all be the canonical names. So, do we need an entry for each of these and then duplicate the nicknames? I wouldn't necessarily be opposed to it but I feel like there could be a better solution.

Basically what we need to represent is a [directed adjacency matrix](https://en.wikipedia.org/wiki/Adjacency_matrix#Directed_graphs). eg there is an NxN matrix, one row and column for each name. There is entry in location (X, Y) if "X is the canonical name for Y".

I don't think there is a better way to represent this in a nice human-editable way than this X,Y,Y,Y,Y format that we have currently. I think if you want to precisely specify the relationship, no matter what you do you're going to have that duplicate information of anne, anna, ana, annie.

**Comment by carltonnorthern** [comment]
> test.pypi

Ahh, wasn't aware of test.pypi.  I see it now in your original post.  I've signed up there also.  Thanks.

**Comment by carltonnorthern** [comment]
> all_names
> I don't think there is a better way to represent this in a nice human-editable way than this X,Y,Y,Y,Y format that we have currently. I think if you want to precisely specify the relationship, no matter what you do you're going to have that duplicate information of anne, anna, ana, annie.

These are good points.

It sounds like sticking with the X,Y,Y,Y,Y format is best but then duplicating rows for multiple canonical names that map to the same nicknames.  That way we can have relationships rather than everything being interchangeable.

**Comment by NickCrews** [comment]
@mdahlman Take a look at #40 to check that I'm going in the right direction

**Pull request merged**
